"""broadcast-wizard — Interactive CLI to discover injection points and generate broadcast.patch.

Helps users find where in the Dexcom APK to inject glucose broadcast code,
then generates a ready-to-use patch file.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any


# Targets that handle incoming sensor/transmitter data
TX_REPOSITORY_PATTERNS = [
    "TxServiceRoomRepository",
    "TxRepository",
    "TransmitterRepository",
]

# Method patterns that handle sensor readings
SAVE_METHOD_PATTERNS = [
    "insertSensorReading",
    "saveReading",
    "saveSensorReading",
    "insertReading",
    "addReading",
    "storeReading",
]

# Class patterns that indicate broadcast-ready code
BROADCAST_PATTERNS = [
    "BROADCAST_ACTION",
    "sendBroadcast",
    "LocalBroadcastManager",
    "IntentFilter",
]


def find_tx_repository(decompiled_dir: str | Path) -> Path | None:
    """Locate the TxServiceRoomRepository.smali (or equivalent) in a decompiled APK."""
    decompiled_dir = Path(decompiled_dir)
    for pattern in TX_REPOSITORY_PATTERNS:
        for smali_file in decompiled_dir.rglob(f"{pattern}.smali"):
            return smali_file
    return None


def find_save_methods(smali_content: str) -> list[dict[str, str]]:
    """Extract save/insert methods that handle sensor readings from a .smali file.

    Returns a list of dicts with 'name' and 'descriptor' for each method.
    """
    methods = []
    # Match .method directives with full signature
    for match in re.finditer(
        r"\.method\s+(?:public|private|protected)?\s*(\w+)\s*\(([^)]*)\)(.*?)(?=\.end\s+method)",
        smali_content,
        re.DOTALL,
    ):
        name = match.group(1)
        params = match.group(2)
        return_type = match.group(3).strip()
        descriptor = f"({params}){return_type}"

        # Filter to likely save/insert methods
        for pattern in SAVE_METHOD_PATTERNS:
            if pattern.lower() in name.lower():
                methods.append({
                    "name": name,
                    "descriptor": descriptor,
                    "params": params,
                    "return_type": return_type,
                })
                break
    return methods


def has_broadcast_code(smali_content: str) -> bool:
    """Check if a .smali file already contains broadcast-related code."""
    for pattern in BROADCAST_PATTERNS:
        if pattern in smali_content:
            return True
    return False


def generate_broadcast_injection(method: dict) -> str:
    """Generate Dexcom-compatible broadcast code snippet for a given method.

    Uses the same approach as the existing broadcast.patch — static field for
    action string + sendBroadcast call after the method body.
    """
    method_name = method["name"]
    # Dexcom G7 internal broadcast action
    action = "com.dexcom.g7.GLUCOSE_READING"

    injection = f"""
    # Generated by broadcast-wizard
    # Inject broadcast after {method_name}
    invoke-static {{p0}}, Lcom/dexcom/coresdk/g7appcore/util/BroadcastHelper;->sendGlucoseBroadcast(Ljava/lang/Object;)V
"""
    return injection.strip()


def generate_broadcast_patch(
    methods: list[dict],
    output_path: str | Path | None = None,
) -> str:
    """Generate a broadcast.patch file for the given methods.

    Creates a patch with:
    1. The original method signature as anchor
    2. Broadcast-injection code appended after the method body

    Returns the patch content (and optionally writes to output_path).
    """
    lines = [
        "# broadcast.patch — generated by broadcast-wizard",
        "# DO NOT EDIT MANUALLY — re-run broadcast-wizard to regenerate",
        "",
    ]

    for method in methods:
        name = method["name"]
        lines.extend([
            "",
            f"# Target method: {name}{method['descriptor']}",
            f"# Injection point: after {name} returns",
            "",
            "# Smali injection code:",
            f"  invoke-static {{p0}}, Lcom/dexcom/coresdk/g7appcore/util/BroadcastHelper;->sendGlucoseBroadcast(Ljava/lang/Object;)V",
            f"# End injection for {name}",
            "",
            f"replace:{name}:{name}    # original method",
        ])

    lines.extend([
        "#",
        "# === DEXCOM G7 GLUCOSE BROADCAST INJECTION ===",
        "#",
        "# This patch adds a broadcast receiver that sends glucose readings to",
        "# external apps (AAPS, NightScout, etc.) whenever new data arrives.",
        "#",
        "# Dexcom G7 broadcast action: com.dexcom.g7.GLUCOSE_READING",
        "# Dexcom G7 extras key: glucose_value_mg_dl",
        "#",
    ])

    # Generate replacement blocks for each method
    for method in methods:
        name = method["name"]
        lines.extend([
            "",
            f"replace:{name}:#BROADCAST_INJECTED#",
        ])

    content = "\n".join(lines)

    if output_path:
        Path(output_path).write_text(content)

    return content


def discover_injection_points(
    decompiled_dir: str | Path,
    repository_name: str = "TxServiceRoomRepository",
) -> dict[str, Any]:
    """Scan a decompiled APK directory for broadcast injection opportunities.

    Returns a report with:
    - repository_found: bool
    - repository_path: str | None
    - methods: list of save/insert methods
    - has_broadcast_intent: bool (already patched?)
    - recommended_injection_method: str | None
    """
    decompiled_dir = Path(decompiled_dir)
    result = {
        "repository_found": False,
        "repository_path": None,
        "methods": [],
        "has_broadcast_intent": False,
        "recommended_injection_method": None,
        "decompiled_dir": str(decompiled_dir),
    }

    repo_path = find_tx_repository(decompiled_dir)
    if repo_path is None:
        return result

    result["repository_found"] = True
    result["repository_path"] = str(repo_path)

    content = repo_path.read_text()
    result["methods"] = find_save_methods(content)
    result["has_broadcast_intent"] = has_broadcast_code(content)

    if result["methods"]:
        result["recommended_injection_method"] = result["methods"][0]["name"]

    return result


def interactive_wizard(decompiled_dir: str | Path) -> str | None:
    """Interactive CLI wizard — ask user to confirm injection points and generate patch.

    This is the main user-facing function that:
    1. Runs discover_injection_points
    2. Asks confirmation for each injection point
    3. Generates broadcast.patch
    4. Returns the patch content
    """
    print("=== Dexcom G7 Broadcast Wizard ===")
    print()

    report = discover_injection_points(decompiled_dir)

    if not report["repository_found"]:
        print("ERROR: TxServiceRoomRepository not found in decompiled APK.")
        print("Did you run 'apktool d' first?")
        return None

    print(f"Found: {report['repository_path']}")
    print(f"Save methods: {', '.join(m['name'] for m in report['methods'])}")

    if report["has_broadcast_intent"]:
        print()
        print("NOTE: This repository already appears to have broadcast code.")
        print("Re-running this wizard will overwrite the existing broadcast.patch.")

    if not report["methods"]:
        print()
        print("WARNING: No save/insert methods found.")
        print("You may need to manually identify the right injection point.")
        return None

    # Auto-generate for now (interactive confirmation would go here)
    print()
    print(f"Will generate broadcast.patch targeting: {report['recommended_injection_method']}")

    patch = generate_broadcast_patch(report["methods"])
    return patch


def main(args: list[str]):
    import argparse
    parser = argparse.ArgumentParser(
        description="Discover injection points and generate broadcast.patch"
    )
    parser.add_argument(
        "decompiled_dir",
        help="Path to decompiled APK directory (from apktool d)",
    )
    parser.add_argument(
        "-o", "--output",
        help="Output path for broadcast.patch (default: patches/broadcast.patch)",
        default="patches/broadcast.patch",
    )
    parser.add_argument(
        "--non-interactive",
        action="store_true",
        help="Skip confirmation prompts and auto-generate",
    )
    opts = parser.parse_args(args)

    report = discover_injection_points(opts.decompiled_dir)

    print("=== Injection Point Discovery ===")
    print(f"Repository found: {report['repository_found']}")
    if report["repository_found"]:
        print(f"Path: {report['repository_path']}")
        print(f"Save methods: {len(report['methods'])} found")
        for m in report["methods"]:
            print(f"  - {m['name']}{m['descriptor']}")
        print(f"Already has broadcast: {report['has_broadcast_intent']}")
        print()

    if not report["repository_found"] or not report["methods"]:
        print("ERROR: Could not find suitable injection points.", file=sys.stderr)
        sys.exit(1)

    patch = generate_broadcast_patch(report["methods"], opts.output)
    print(f"Generated: {opts.output}")
    print()
    print("Next steps:")
    print(f"  1. Review: cat {opts.output}")
    print(f"  2. Test:   python3 -m tools patch-staging <apk> --dry-run")
    print(f"  3. Apply:  python3 -m tools patch-staging <apk>")
